"""setup db

Revision ID: dfc3704b0e83
Revises:
Create Date: 2026-04-14 18:01:20.415913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dfc3704b0e83"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "housing_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("num_rooms", sa.Integer(), nullable=False),
        sa.Column("num_bathrooms", sa.Float(), nullable=False),
        sa.Column("sq_feet", sa.Integer(), nullable=False),
        sa.Column("aesthetic", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("year_built", sa.Integer(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("has_garage", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
    )
    op.create_index(
        op.f("ix_housing_data_city"), "housing_data", ["city"], unique=False
    )
    op.create_index(
        op.f("ix_housing_data_price"), "housing_data", ["price"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_housing_data_price"), table_name="housing_data")
    op.drop_index(op.f("ix_housing_data_city"), table_name="housing_data")
    op.drop_table("housing_data")
    # ### end Alembic commands ###
